# Generated by Django 4.0.5 on 2023-08-07 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='SignUpUser',
        ),
    ]
