# Generated by Django 4.0.5 on 2023-08-07 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_user_signupuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SignUpUser',
            new_name='User',
        ),
    ]
