# Generated by Django 4.0.5 on 2023-08-09 12:27

import contextlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_signupuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default=contextlib.nullcontext, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=contextlib.nullcontext, max_length=20),
        ),
    ]
