# Generated by Django 4.0.5 on 2023-08-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=100)),
                ('product_category', models.CharField(choices=[('t-shirt', 'T-SHIRT'), ('jeans', 'JEANS'), ('hoodie', 'HOODIE'), ('shoes', 'SHOES'), ('man-necklaces', 'MAN-NECKLACES')], default=None, max_length=50)),
                ('product_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9)),
                ('product_image', models.ImageField(upload_to='images/products')),
                ('product_description', models.TextField(blank=True, max_length=2000)),
            ],
        ),
    ]
