# Generated by Django 4.0.5 on 2023-08-11 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tel', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('date', models.DateField(blank=True)),
                ('cvc', models.CharField(blank=True, max_length=50)),
                ('name_card', models.CharField(blank=True, max_length=50)),
                ('states', models.CharField(blank=True, max_length=50)),
                ('zip', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
