# Generated by Django 4.0.5 on 2023-08-11 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='states',
            new_name='continents',
        ),
    ]
