# Generated by Django 4.0.5 on 2023-08-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_payment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cart',
            field=models.BooleanField(default=False),
        ),
    ]
