# Generated by Django 4.0.5 on 2023-08-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_product_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_quantity',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
